"""added event kind

Revision ID: 373cfdcf0537
Revises: 4f0aa60fec49
Create Date: 2023-12-11 11:06:15.844290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373cfdcf0537'
down_revision = '4f0aa60fec49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_date', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('public', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'public')
    op.drop_column('events', 'event_date')
    # ### end Alembic commands ###
