"""+class_id

Revision ID: 3938f0b34122
Revises: 63146c8b0889
Create Date: 2024-01-11 19:18:42.904882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3938f0b34122'
down_revision = '63146c8b0889'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'class_id')
    # ### end Alembic commands ###
