"""more intervals

Revision ID: 3970c182df48
Revises: 3938f0b34122
Create Date: 2024-02-10 21:01:00.499521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3970c182df48'
down_revision = '3938f0b34122'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'intervals',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'intervals',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
