"""event -nullability most fields

Revision ID: 3d9505bfb3ca
Revises: 1c4ea1567b39
Create Date: 2023-12-18 13:17:01.532482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d9505bfb3ca'
down_revision = '1c4ea1567b39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('user_id', sa.String(), nullable=True))
    op.drop_constraint('applications_applicant_id_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('applications', 'applicant_id')
    op.alter_column('events', 'quota',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('events', 'time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('events', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('events', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('events', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('events', 'time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('events', 'quota',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.add_column('applications', sa.Column('applicant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_applicant_id_fkey', 'applications', 'users', ['applicant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('applications', 'user_id')
    # ### end Alembic commands ###
