"""changed public col name

Revision ID: 48385f4fedd4
Revises: e1087be9f304
Create Date: 2023-12-13 10:55:34.832825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48385f4fedd4'
down_revision = 'e1087be9f304'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('isPublic', sa.Boolean(), nullable=False))
    op.drop_column('events', 'public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('events', 'isPublic')
    # ### end Alembic commands ###
