"""application -platform

Revision ID: 4875423302aa
Revises: d7475cc0cebe
Create Date: 2023-12-18 17:52:29.867489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4875423302aa'
down_revision = 'd7475cc0cebe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
