"""+event_name

Revision ID: 905c33bc1e5c
Revises: 3d9505bfb3ca
Create Date: 2023-12-18 13:18:27.821626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905c33bc1e5c'
down_revision = '3d9505bfb3ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
