"""changed col name

Revision ID: 93da41301997
Revises: ea981d2c9604
Create Date: 2023-12-13 10:46:57.323500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93da41301997'
down_revision = 'ea981d2c9604'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.drop_column('events', 'event_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('events', 'timestamp')
    # ### end Alembic commands ###
