"""edited platform type

Revision ID: ab07cf68888d
Revises: 373cfdcf0537
Create Date: 2023-12-11 11:11:42.129166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab07cf68888d'
down_revision = '373cfdcf0537'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'platform', type_=sa.VARCHAR(4), existing_type=sa.SmallInteger())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'platform', existing_type=sa.VARCHAR(4), type_=sa.SmallInteger())
    # ### end Alembic commands ###
