"""user +phone

Revision ID: cb4f33df8c12
Revises: 905c33bc1e5c
Create Date: 2023-12-18 17:50:14.160223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4f33df8c12'
down_revision = '905c33bc1e5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('children_name', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('applications', 'phone_number')
    op.drop_column('applications', 'children_name')
    # ### end Alembic commands ###
