"""added client name

Revision ID: ea981d2c9604
Revises: ab07cf68888d
Create Date: 2023-12-11 11:20:31.789962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea981d2c9604'
down_revision = 'ab07cf68888d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('client_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'client_name')
    # ### end Alembic commands ###
